from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1099, 725)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalWidget_2.setStyleSheet("background-color: rgb(255, 251, 207);")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalWidget_21 = QtWidgets.QWidget(parent=self.verticalWidget_2)
        self.verticalWidget_21.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.verticalWidget_21.setObjectName("verticalWidget_21")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalWidget_21)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalWidget = QtWidgets.QWidget(parent=self.verticalWidget_21)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setStyleSheet("border-image: url(:/bulbasur.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_11.addWidget(self.graphicsView)
        self.verticalLayout_5.addWidget(self.verticalWidget)
        self.label = QtWidgets.QLabel(parent=self.verticalWidget_21)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setTabletTracking(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.editar = QtWidgets.QPushButton(parent=self.verticalWidget_21)
        self.editar.setObjectName("editar")
        self.verticalLayout_5.addWidget(self.editar)
        self.horizontalLayout_3.addWidget(self.verticalWidget_21)
        self.verticalWidget_3 = QtWidgets.QWidget(parent=self.verticalWidget_2)
        self.verticalWidget_3.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalWidget1 = QtWidgets.QWidget(parent=self.verticalWidget_3)
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalWidget1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.graphicsView_3 = QtWidgets.QGraphicsView(parent=self.verticalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_3.sizePolicy().hasHeightForWidth())
        self.graphicsView_3.setSizePolicy(sizePolicy)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_12.addWidget(self.graphicsView_3)
        self.verticalLayout_6.addWidget(self.verticalWidget1)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalWidget_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.editar_2 = QtWidgets.QPushButton(parent=self.verticalWidget_3)
        self.editar_2.setObjectName("editar_2")
        self.verticalLayout_6.addWidget(self.editar_2)
        self.horizontalLayout_3.addWidget(self.verticalWidget_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalWidget_22 = QtWidgets.QWidget(parent=self.verticalWidget_2)
        self.verticalWidget_22.setStyleSheet("\n"
"background-color: rgb(206, 206, 206);")
        self.verticalWidget_22.setObjectName("verticalWidget_22")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalWidget_22)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.graphicsView_5 = QtWidgets.QGraphicsView(parent=self.verticalWidget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_5.sizePolicy().hasHeightForWidth())
        self.graphicsView_5.setSizePolicy(sizePolicy)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.verticalLayout_15.addWidget(self.graphicsView_5)
        self.verticalLayout_8.addLayout(self.verticalLayout_15)
        self.label_5 = QtWidgets.QLabel(parent=self.verticalWidget_22)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.verticalWidget_22)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_8.addWidget(self.pushButton_3)
        self.horizontalLayout_4.addWidget(self.verticalWidget_22)
        self.verticalWidget_4 = QtWidgets.QWidget(parent=self.verticalWidget_2)
        self.verticalWidget_4.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.verticalWidget_4.setObjectName("verticalWidget_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalWidget_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.graphicsView_6 = QtWidgets.QGraphicsView(parent=self.verticalWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_6.sizePolicy().hasHeightForWidth())
        self.graphicsView_6.setSizePolicy(sizePolicy)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.verticalLayout_16.addWidget(self.graphicsView_6)
        self.verticalLayout_10.addLayout(self.verticalLayout_16)
        self.label_6 = QtWidgets.QLabel(parent=self.verticalWidget_4)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.verticalWidget_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_10.addWidget(self.pushButton_4)
        self.horizontalLayout_4.addWidget(self.verticalWidget_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.verticalWidget_2)
        self.verticalWidget2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalWidget2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.verticalWidget2.setStyleSheet("background-color: rgb(255, 251, 207);")
        self.verticalWidget2.setObjectName("verticalWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget2)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalWidget3 = QtWidgets.QWidget(parent=self.verticalWidget2)
        self.verticalWidget3.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.verticalWidget3.setObjectName("verticalWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalWidget4 = QtWidgets.QWidget(parent=self.verticalWidget3)
        self.verticalWidget4.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.verticalWidget4.setObjectName("verticalWidget4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalWidget4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=self.verticalWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_2.sizePolicy().hasHeightForWidth())
        self.graphicsView_2.setSizePolicy(sizePolicy)
        self.graphicsView_2.setStyleSheet("border-image: url(:/bulbasur.png);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_14.addWidget(self.graphicsView_2)
        self.verticalLayout_4.addWidget(self.verticalWidget4)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalWidget3)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.cambiarEquipo = QtWidgets.QPushButton(parent=self.verticalWidget3)
        self.cambiarEquipo.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.cambiarEquipo.setObjectName("cambiarEquipo")
        self.verticalLayout_4.addWidget(self.cambiarEquipo)
        self.verticalLayout.addWidget(self.verticalWidget3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalWidget_4 = QtWidgets.QWidget(parent=self.verticalWidget2)
        self.horizontalWidget_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalWidget_4.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.horizontalWidget_4.setObjectName("horizontalWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.volverInicio = QtWidgets.QPushButton(parent=self.horizontalWidget_4)
        self.volverInicio.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.volverInicio.setObjectName("volverInicio")
        self.volverInicio.clicked.connect(self.volver_a_partidas)
        self.horizontalLayout_5.addWidget(self.volverInicio)
        self.empezarJugar = QtWidgets.QPushButton(parent=self.horizontalWidget_4)
        self.empezarJugar.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.empezarJugar.setObjectName("empezarJugar")
        self.horizontalLayout_5.addWidget(self.empezarJugar)
        self.verticalLayout.addWidget(self.horizontalWidget_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2.addWidget(self.verticalWidget2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.MainWindow = MainWindow

    def volver_a_partidas(self):
        self.MainWindow.close()
            
        from seleccion_partida import SelPartida
        self.registro_window = SelPartida()
        self.registro_window.setupUi(self.MainWindow) 
        self.MainWindow.show()
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Equipo 1"))
        self.editar.setText(_translate("MainWindow", "Editar equipo"))
        self.label_2.setText(_translate("MainWindow", "Equipo 2"))
        self.editar_2.setText(_translate("MainWindow", "PushButton"))
        self.label_5.setText(_translate("MainWindow", "Equipo 3"))
        self.pushButton_3.setText(_translate("MainWindow", "Editar equipo"))
        self.label_6.setText(_translate("MainWindow", "Equipo 4"))
        self.pushButton_4.setText(_translate("MainWindow", "Editar equipo"))
        self.label_4.setText(_translate("MainWindow", "Equipo 1"))
        self.cambiarEquipo.setText(_translate("MainWindow", "Cambiar equipo"))
        self.volverInicio.setText(_translate("MainWindow", "Volver al inicio"))
        self.empezarJugar.setText(_translate("MainWindow", "Empezar a jugar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
